Tic tac toe game
FelipeEnne/Tic-Tac-Toe-JavaScript pull request #1
Opened 2020-02-26 17:15 UTC by FelipeEnne

This is the first draft of the project.

The tic-tac-toe it was implemented.

Kindly review the project. We will be waiting for your response.

2020-02-27 02:01 UTC, bellom commented
> This is the first draft of the project.
> 
> The tic-tac-toe it was implemented.
> 
> Kindly review the project. We will be waiting for your response.

You should add the implementation you did in the project 🙂 
Kindly edit 👍

2020-02-27 02:41 UTC, bellom requested changes
## Hi @ :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**_1. I am unable to play the game, click event Listener seems not working.(nothing happens after clicking the cells to play the game)
2. Kindly check out my comments below._**

**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-02-27 02:41 UTC, bellom commented on .eslintrc.json
> +    "no-alert": "off"
You made some changes in this file, check out the [microverse-linter-config](https://github.com/microverseinc/linters-config/tree/master/javascript)
![image](https://user-images.githubusercontent.com/31897434/73417568-ca44bd00-4318-11ea-8a5e-fedabd629b8c.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/

2020-02-27 02:41 UTC, bellom commented on eslintrc.json
> +{
kindly delete this file, it seems you're not using right?

2020-02-27 02:41 UTC, bellom commented on js/index.js
> +let playTurn = 1;
we shouldn't make use of global code, let use modules or factories.
![image](https://user-images.githubusercontent.com/31897434/75405859-2b0ee780-590f-11ea-84e0-e2e66e5130ed.png)
https://www.theodinproject.com/courses/javascript/lessons/tic-tac-toe-javascript

2020-02-27 02:41 UTC, bellom commented on js/index.js
> +const gameBoard = (space, value) => {
Note: The main goal of this project is for us to practice Factory Functions and The Module Pattern from the [previous section](https://www.theodinproject.com/courses/javascript/lessons/factory-functions-and-the-module-pattern) in the curriculum.
we should have `game`, `gameBoard`, and `player` objects
![image](https://user-images.githubusercontent.com/31897434/75406219-33b3ed80-5910-11ea-83e6-3d2be95b855d.png)

2020-02-27 02:41 UTC, bellom commented on js/index.js
> +function render(board) {
Let separate the DOM from application logic, you can create another file for DOM.

![image](https://user-images.githubusercontent.com/31897434/73420341-70e18b80-4322-11ea-840a-fa14e04b592b.png)

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59623090/

2020-02-28 17:35 UTC, mcrd25 approved these changes
# Changes Approved 💪 🎊 🤓 

Hey Team! 👋 

Great job implementing the changes! 👏 👍 

#### suggested changes [OPTIONAL]
- The correct player's turn when playing vs AI does not update accurately. Address this [OPTIONAL]

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2020-02-28 17:59 UTC, merged